### ISSUE TITLE
TLS ciphers and protocols settings

### ISSUE THREAD

**Issue by 532910** [processone/eturnal#6]
Please add settings to control allowed TLS ciphers and protocols.

**Comment by weiss** [comment]
Do you have an actual use case for controlling TLS parameters manually? I'm asking because these days, TLS is not commonly used for securing TURN communication, but rather just to circumvent restrictive firewalls. The data is transmitted via UDP to the TURN peer anyway, and it's usually end-to-end encrypted. As one of my goals with eturnal is to keep it (and the documentation) as simple as possible, I'd prefer not to add configuration options just for the sake of it.

However, I'd be more open to this if we ever add support for persistent credentials, as one use case of TLS could then be to hide the TURN credentials (esp. the username) from an attacker.

That said, I'm open to be convinced of other use cases.

**Comment by 532910** [comment]
TLSv1 and TLSv1.1 are deprecated nowadays:

`testssl turnserver:5349`:
```
...
 TLS 1      offered (deprecated)
 TLS 1.1    offered (deprecated)
...
 Obsolete CBC ciphers (AES, ARIA etc.)         offered
...
```

**Comment by weiss** [comment]
Making a test tool happy makes sense of you have an actual reason for performing that test, and my question was whether you do 🙂

**Comment by 532910** [comment]
I think of testssl as a scope tool to look service configuration and reveal flaws rather than a test tool.

While security can have a lot of grades (shown with Mozilla Observatory or Qualys test) the result is binary: it is reliable or not. TLSv1 and TLSv1.1 are not reliable. rfc7525 says it `SHOULD NOT` be used.

To keep it simple is a good goal, but TLS versions below 1.2 must be killed.

**Comment by Neustradamus** [comment]
@weiss: Have you looked for the feature?
