### ISSUE TITLE
eturnal not working when clients come from Home/Enterprise Networks, but OK with Mobile Data Networks

### ISSUE THREAD

**Issue by evolkovgit** [processone/eturnal#79]
Hello Eturnal team! 
I developed a "voice chat app" with Node.js and socket.io. I followed "Quick Start" and run eturnal server as non-root user (the fact I like a lot) on my AWS Ubuntu 20.04  instance with public IP Address. So, I tried my app as a client to eturnal server. It worked perfectly when two clients come from Mobile Data Networks. I understand it was P2P case. However when clients come from HOME/Enterprise network, it does not work: the clients cannot hear each other. I tried several HOME/ENTERPRISE networks with the same result.  I tried both TCP and UDP with no success. I opened all the possible ports on my instance (AWS Security group) like TCP/UDP 3478, ports 49152-65535 (both TCP and UDP) with no success. I understand it is something connected to the TURN server, not doing its "relying" job, but I do not know why it happens.  I also understand: it is about NAT, but I assume your TURN server must relay the traffic (via outgoing) in such cases, but it does not.  Attached are the logs for "good" and "bad" cases . Also I use static credentials for now, but I love ephemeral credentials on the fly, will use them later and this will help to prove the use case in my  organization)

[eturnalBadWith1MobileAndOtherLAN.log.txt](https://github.com/user-attachments/files/17199926/eturnalBadWith1MobileAndOtherLAN.log.txt)
[eturnalGoodWith2MobileDataClients.log.txt](https://github.com/user-attachments/files/17199927/eturnalGoodWith2MobileDataClients.log.txt)
[eturnal.yml.txt](https://github.com/user-attachments/files/17199928/eturnal.yml.txt)

Could you please help me? 
Thank you, Eugene

**Comment by weiss** [comment]
The log lines you've shown indicate that TURN sessions are created successfully but no traffic was received on the relay address/port (even in the "good" case).  Therefore, I'd start by checking UDP connectivity on your `relay_ipv4_addr`, e.g. by running the following command on the server:

```sh
sudo tcpdump -i any udp port 50000
```

And then calling `netcat` on a remote client (e.g., a Linux laptop):

```sh
echo Test | netcat -u turn.example.com 50000
```

(This is assuming [openbsd-netcat][1]. With the ["traditional" netcat][2] implementation you'd use `-U` instead of `-u` to enable UDP mode.)

The `netcat` call should produce a line of `tcpdump` output that looks like:

```
12:23:18.625178 eth0  In  IP client.example.net.40123 > turn.example.com.50000: UDP, length 5
```

Does that work?

[1]: https://packages.debian.org/stable/netcat-openbsd
[2]: https://packages.debian.org/stable/netcat-traditional

**Comment by weiss** [comment]
Just by the way:

> ports 49152-65535 (both TCP and UDP)

You only need UDP here, TCP is never used on that port range no matter what.

**Comment by evolkovgit** [comment]
Holger,

Thank you for your help.  After hard debugging work, I found that the reason was a bug in my client code. I am closing this issue.
Eugene
