### ISSUE TITLE
Erlang port mapper daemon (epmd) port is open by default

### ISSUE THREAD

**Issue by passw0rd123** [processone/eturnal#9]
When using the `.deb` package on Debian the **epmd** Port is open to the public.

```
    0.0.0.0:4369    0.0.0.0:*    users:(("epmd",pid=13803,fd=3))
```

If the **Erlang port mapper daemon** (epmd) is needed it should listen on localhost per default to prevent public access to this service.

If it's not possible to limit access to this port, I strongly recommend to add an advice to the documentation to block this port in the servers local firewall.

**Comment by weiss** [comment]
> If the *Erlang port mapper daemon* (epmd) is needed it should listen on localhost per default to prevent public access to this service.

This is what we did initially.  We reverted to epmd's default behavior of listening on `INADDR_ANY` in commit 3a65d40818058137ee95e5af07a7701669e691f3, since epmd can unfortunately fail to startup on IPv4-only systems if its bound to a specific address.

> If it's not possible to limit access to this port

It's [possible][1], admins could for example call `systemctl edit eturnal` and add the following line to the `[Service]` section:
```
Environment="ERL_EPMD_ADDRESS=127.0.0.1"
```
> add an advice to the documentation

Yes, I was going to do that and forgot.  Will do, thanks.

[1]: https://github.com/erlang/otp/commit/bcf3b3d0d589666575d9b044d0779be2e40e1762

**Comment by weiss** [comment]
> If the **Erlang port mapper daemon** (epmd) is needed it should listen on localhost per default to prevent public access to this service.

With Erlang/OTP 23.1+ and Rebar3 3.18.0+, there's [a way to avoid EPMD][1] altogether.  Our Linux packages and Docker images have been adjusted accordingly.

> epmd can unfortunately fail to start up on IPv4-only systems if it's bound to a specific address.

This issue has been [fixed][2] in Erlang/OTP 25+, so we'll probably revert to letting EPMD listen on `127.0.0.1` by default (in the case where an EPMD process _is_ spawned by eturnal).

[1]: https://eturnal.net/documentation/#ERL_DIST_PORT
[2]: https://github.com/erlang/otp/commit/e8c9e121c1b286ecddd572190c2a1fe72adc97bb
